spring.application.name=Application

#database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Zoho_InventoryT?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pethmin2296

#JPA Settings
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


