/**
 * category.js — Category Management: CRUD operations
 *
 * Real backend API: http://localhost:8080/api/category
 *
 * CategoryDTO structure:
 * {
 *   categoryId: int, (auto-generated by DB identity on create)
 *   categoryName: string,
 *   categoryDescription: string
 * }
 */

// -------------------------------------------------------
// Module state
// -------------------------------------------------------
let allCategories = [];         // Full list from backend
let filteredCategories = [];    // After search filter
let categoryToDelete = null;   // ID pending delete confirmation
let editingCategoryID = null;  // int ID being edited (null = adding new)

/* =====================================================
   PAGE INITIALISATION
   ===================================================== */
function initCategoryPage() {
    // Attach static event listeners (modal, search, buttons)
    document.getElementById('btn-add-category')?.addEventListener('click', openAddCategoryModal);
    document.getElementById('cat-search-input')?.addEventListener('input', onCategorySearchInput);
    document.getElementById('category-form')?.addEventListener('submit', onCategoryFormSubmit);
    document.getElementById('cat-modal-cancel-btn')?.addEventListener('click', closeCategoryModal);
    document.getElementById('cat-modal-close-btn')?.addEventListener('click', closeCategoryModal);
    document.getElementById('cat-confirm-cancel-btn')?.addEventListener('click', closeCategoryConfirm);
    document.getElementById('cat-confirm-delete-btn')?.addEventListener('click', confirmDeleteCategory);

    // Close modal/confirm on overlay click
    document.getElementById('category-modal')?.addEventListener('click', (e) => {
        if (e.target.id === 'category-modal') closeCategoryModal();
    });
    document.getElementById('cat-delete-confirm')?.addEventListener('click', (e) => {
        if (e.target.id === 'cat-delete-confirm') closeCategoryConfirm();
    });

    // Load data
    loadCategoriesData();
}

/* =====================================================
   LOAD ALL CATEGORIES
   ===================================================== */
async function loadCategoriesData() {
    showCategorySkeleton();

    try {
        allCategories = await api.get('/category');
        filteredCategories = [...allCategories];
        renderCategoryTableData(filteredCategories);
        updateCategoryCount(filteredCategories.length);
    } catch (err) {
        showCategoryTableError(err.message);
    }
}

/* =====================================================
   SEARCH / FILTER (client-side)
   ===================================================== */
function onCategorySearchInput(e) {
    const q = e.target.value.trim().toLowerCase();
    if (!q) {
        filteredCategories = [...allCategories];
    } else {
        filteredCategories = allCategories.filter(c => {
            const idStr = String(c.categoryId || '').toLowerCase();
            const nm = (c.categoryName || '').toLowerCase();
            const desc = (c.categoryDescription || '').toLowerCase();
            return idStr.includes(q) || nm.includes(q) || desc.includes(q);
        });
    }
    renderCategoryTableData(filteredCategories);
    updateCategoryCount(filteredCategories.length);
}

function updateCategoryCount(count) {
    const el = document.getElementById('category-count');
    if (el) el.textContent = `${count} categor${count !== 1 ? 'ies' : 'y'}`;
}

/* =====================================================
   RENDER TABLE
   ===================================================== */
function renderCategoryTableData(categories) {
    const tbody = document.getElementById('categories-tbody');
    if (!tbody) return;

    if (!categories || categories.length === 0) {
        tbody.innerHTML = `
            <tr>
                <td colspan="4" class="empty-table-cell">
                    <div class="empty-state">
                        <div class="empty-state-icon">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 0 0 3 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 0 0 5.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 0 0 9.568 3Z"/>
                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6Z"/>
                            </svg>
                        </div>
                        <div class="empty-state-title">${allCategories.length === 0 ? 'No categories yet' : 'No matching categories'}</div>
                        <div class="empty-state-msg">${allCategories.length === 0 ? 'Click "Add Category" to create your first category.' : 'Try adjusting your search criteria.'}</div>
                    </div>
                </td>
            </tr>`;
        return;
    }

    tbody.innerHTML = categories.map(c => {
        const rawId = c.categoryId;
        const formattedId = `CAT-${String(rawId).padStart(3, '0')}`;
        const name = c.categoryName || 'Unnamed Category';
        const desc = c.categoryDescription || '—';
        const initials = name.substring(0, 2).toUpperCase() || 'CT';
        const color = avatarColor(String(rawId));

        return `
            <tr>
                <td>
                    <div class="avatar-cell">
                        <div class="avatar" style="background:${color}">${escapeHtml(initials)}</div>
                        <div class="avatar-info">
                            <span class="user-name">${escapeHtml(name)}</span>
                            <span class="user-id">${escapeHtml(formattedId)}</span>
                        </div>
                    </div>
                </td>
                <td class="hide-mobile">
                    <span style="font-weight:600;color:#E2E8F0">${escapeHtml(name)}</span>
                </td>
                <td class="hide-mobile">
                    <span style="color:var(--color-text-muted);font-size:13px;">${escapeHtml(desc)}</span>
                </td>
                <td>
                    <div class="action-buttons">
                        <button class="action-btn action-edit" title="Edit Category" onclick="openEditCategoryModal(${rawId})">
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Z"/>
                            </svg>
                        </button>
                        <button class="action-btn action-delete" title="Delete Category" onclick="openCategoryDeleteConfirm(${rawId}, '${escapeHtml(name)}')">
                            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
                            </svg>
                        </button>
                    </div>
                </td>
            </tr>`;
    }).join('');
}

function showCategorySkeleton() {
    const tbody = document.getElementById('categories-tbody');
    if (!tbody) return;
    tbody.innerHTML = Array(4).fill(0).map(() => `
        <tr>
            <td><div class="skeleton" style="height:36px;width:180px"></div></td>
            <td class="hide-mobile"><div class="skeleton" style="height:14px;width:140px"></div></td>
            <td class="hide-mobile"><div class="skeleton" style="height:14px;width:180px"></div></td>
            <td><div class="skeleton" style="height:30px;width:66px"></div></td>
        </tr>`).join('');
}

function showCategoryTableError(msg) {
    const tbody = document.getElementById('categories-tbody');
    if (!tbody) return;
    tbody.innerHTML = `
        <tr>
            <td colspan="4" class="empty-table-cell">
                <div class="empty-state">
                    <div class="empty-state-title" style="color:var(--color-danger)">Failed to load categories</div>
                    <div class="empty-state-msg">${escapeHtml(msg)}</div>
                    <button class="btn btn-outline btn-sm" style="margin-top:12px" onclick="loadCategoriesData()">Try Again</button>
                </div>
            </td>
        </tr>`;
}

/* =====================================================
   MODALS: OPEN / CLOSE
   ===================================================== */
function openAddCategoryModal() {
    editingCategoryID = null;
    clearCategoryForm();

    const idField   = document.getElementById('field-categoryId');
    const idBadge   = document.getElementById('categoryID-badge');
    const idDisplay = document.getElementById('categoryID-display');
    if (idField)   idField.value           = '0';
    if (idBadge)   idBadge.textContent     = 'Auto-generated';
    if (idDisplay) idDisplay.style.display = 'block';

    const titleEl    = document.getElementById('cat-modal-title');
    const subtitleEl = document.getElementById('cat-modal-subtitle');
    const btnText    = document.getElementById('cat-submit-btn-text');
    if (titleEl)    titleEl.textContent    = 'Add New Category';
    if (subtitleEl) subtitleEl.textContent = 'Fill in parts category details';
    if (btnText)    btnText.textContent    = 'Add Category';

    const modal = document.getElementById('category-modal');
    if (modal) {
        if (modal.parentElement !== document.body) document.body.appendChild(modal);
        modal.classList.add('open');
        modal.classList.add('show');
        modal.style.display      = 'flex';
        modal.style.opacity      = '1';
        modal.style.pointerEvents = 'all';
        modal.style.zIndex       = '99999';
    }
    setTimeout(() => document.getElementById('field-cat-name')?.focus(), 60);
}

function openEditCategoryModal(id) {
    const c = allCategories.find(x => x.categoryId === id);
    if (!c) { showToast('Category not found', '', 'error'); return; }

    editingCategoryID = id;
    clearCategoryForm();

    const idField   = document.getElementById('field-categoryId');
    const idBadge   = document.getElementById('categoryID-badge');
    const idDisplay = document.getElementById('categoryID-display');
    if (idField)   idField.value           = String(id);
    if (idBadge)   idBadge.textContent     = `CAT-${String(id).padStart(3, '0')}`;
    if (idDisplay) idDisplay.style.display = 'block';

    const nameField = document.getElementById('field-cat-name');
    const descField = document.getElementById('field-cat-desc');
    if (nameField) nameField.value = c.categoryName || '';
    if (descField) descField.value = c.categoryDescription || '';

    const titleEl    = document.getElementById('cat-modal-title');
    const subtitleEl = document.getElementById('cat-modal-subtitle');
    const btnText    = document.getElementById('cat-submit-btn-text');
    if (titleEl)    titleEl.textContent    = 'Edit Category';
    if (subtitleEl) subtitleEl.textContent = `Editing ${c.categoryName || ''}`;
    if (btnText)    btnText.textContent    = 'Save Changes';

    const modal = document.getElementById('category-modal');
    if (modal) {
        if (modal.parentElement !== document.body) document.body.appendChild(modal);
        modal.classList.add('open');
        modal.classList.add('show');
        modal.style.display      = 'flex';
        modal.style.opacity      = '1';
        modal.style.pointerEvents = 'all';
        modal.style.zIndex       = '99999';
    }
    setTimeout(() => document.getElementById('field-cat-name')?.focus(), 60);
}

function closeCategoryModal() {
    const modal = document.getElementById('category-modal');
    if (modal) {
        modal.classList.remove('open');
        modal.classList.remove('show');
        modal.style.display = 'none';
        modal.style.opacity = '0';
        modal.style.pointerEvents = 'none';
    }
    clearCategoryForm();
    editingCategoryID = null;
}

function clearCategoryForm() {
    ['field-cat-name', 'field-cat-desc'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.value = '';
    });
    const dispEl = document.getElementById('categoryID-display');
    if (dispEl) dispEl.style.display = 'none';
    document.querySelectorAll('#category-form .form-control').forEach(el => el.classList.remove('error'));
    document.querySelectorAll('#category-form .form-error').forEach(el => { el.classList.remove('show'); el.textContent = ''; });
}

/* =====================================================
   DELETE CONFIRMATION
   ===================================================== */
function openCategoryDeleteConfirm(id, name) {
    categoryToDelete = id;
    const nameEl = document.getElementById('cat-delete-name');
    if (nameEl) nameEl.textContent = name;
    const modal = document.getElementById('cat-delete-confirm');
    if (modal) {
        if (modal.parentElement !== document.body) document.body.appendChild(modal);
        modal.classList.add('open');
        modal.classList.add('show');
        modal.style.display = 'flex';
        modal.style.opacity = '1';
        modal.style.pointerEvents = 'all';
        modal.style.zIndex = '99999';
    }
}

function closeCategoryConfirm() {
    const modal = document.getElementById('cat-delete-confirm');
    if (modal) {
        modal.classList.remove('open');
        modal.classList.remove('show');
        modal.style.display = 'none';
    }
    categoryToDelete = null;
}

async function confirmDeleteCategory() {
    if (categoryToDelete === null || categoryToDelete === undefined) return;
    const btn = document.getElementById('cat-confirm-delete-btn');
    setButtonLoading(btn, true, 'Deleting...');

    try {
        await api.delete('/category/' + categoryToDelete);
        allCategories = allCategories.filter(c => c.categoryId !== categoryToDelete);
        filteredCategories = filteredCategories.filter(c => c.categoryId !== categoryToDelete);
        renderCategoryTableData(filteredCategories);
        updateCategoryCount(filteredCategories.length);
        closeCategoryConfirm();
        showToast('Category deleted', 'The category has been removed successfully.', 'success');
    } catch (err) {
        showToast('Delete failed', err.message, 'error');
    } finally {
        setButtonLoading(btn, false);
    }
}

/* =====================================================
   FORM SUBMIT (ADD / EDIT)
   ===================================================== */
async function onCategoryFormSubmit(e) {
    e.preventDefault();
    if (!validateCategoryForm()) return;

    const btn = document.getElementById('cat-save-btn');
    setButtonLoading(btn, true);

    const payload = buildCategoryDTO();

    try {
        if (editingCategoryID !== null) {
            const updated = await api.put('/category', payload);
            const idx = allCategories.findIndex(c => c.categoryId === editingCategoryID);
            if (idx !== -1) allCategories[idx] = updated;
        } else {
            // Note: For create, categoryId is 0 or auto-generated by DB identity
            const created = await api.post('/category', payload);
            allCategories.unshift(created);
        }

        filteredCategories = [...allCategories];
        renderCategoryTableData(filteredCategories);
        updateCategoryCount(filteredCategories.length);
        closeCategoryModal();
        showToast(
            editingCategoryID !== null ? 'Category updated' : 'Category added',
            `${payload.categoryName} was ${editingCategoryID !== null ? 'updated' : 'added'} successfully.`,
            'success'
        );
    } catch (err) {
        showToast('Operation failed', err.message, 'error');
    } finally {
        setButtonLoading(btn, false);
    }
}

function buildCategoryDTO() {
    const idVal = parseInt(document.getElementById('field-categoryId').value || '0', 10);
    return {
        categoryId: editingCategoryID !== null ? editingCategoryID : 0,
        categoryName: document.getElementById('field-cat-name').value.trim(),
        categoryDescription: document.getElementById('field-cat-desc').value.trim()
    };
}

function validateCategoryForm() {
    let valid = true;
    const rules = [
        { id: 'field-cat-name', err: 'err-cat-name', msg: 'Category name is required' },
        { id: 'field-cat-desc', err: 'err-cat-desc', msg: 'Description is required' }
    ];

    rules.forEach(r => {
        const input = document.getElementById(r.id);
        const errEl = document.getElementById(r.err);
        if (!input) return;

        const val = input.value.trim();
        let errorMsg = '';

        if (!val) errorMsg = r.msg;

        if (errorMsg) {
            input.classList.add('error');
            if (errEl) { errEl.textContent = errorMsg; errEl.classList.add('show'); }
            valid = false;
        } else {
            input.classList.remove('error');
            if (errEl) errEl.classList.remove('show');
        }
    });

    return valid;
}

// Expose handlers globally
window.initCategoryPage = initCategoryPage;
window.openAddCategoryModal = openAddCategoryModal;
window.openEditCategoryModal = openEditCategoryModal;
window.closeCategoryModal = closeCategoryModal;
window.openCategoryDeleteConfirm = openCategoryDeleteConfirm;
window.closeCategoryConfirm = closeCategoryConfirm;
window.confirmDeleteCategory = confirmDeleteCategory;
window.loadCategoriesData = loadCategoriesData;
